// Generated by CoffeeScript 1.10.0
(function() {
  var LineBuffer, Stream, async, exec, execFile, fs, getUserLocale, getUserShell, loginExec, makeTemporaryFilename, parseEnv, path, quote, readAndUnlink,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  fs = require("fs");

  path = require("path");

  async = require("async");

  execFile = require("child_process").execFile;

  Stream = require("stream").Stream;

  exports.LineBuffer = LineBuffer = (function(superClass) {
    extend(LineBuffer, superClass);

    function LineBuffer(stream1) {
      var self;
      this.stream = stream1;
      this.readable = true;
      this._buffer = "";
      self = this;
      this.stream.on('data', function() {
        var args;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return self.write.apply(self, args);
      });
      this.stream.on('end', function() {
        var args;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return self.end.apply(self, args);
      });
    }

    LineBuffer.prototype.write = function(chunk) {
      var index, line, results;
      this._buffer += chunk;
      results = [];
      while ((index = this._buffer.indexOf("\n")) !== -1) {
        line = this._buffer.slice(0, index);
        this._buffer = this._buffer.slice(index + 1, this._buffer.length);
        results.push(this.emit('data', line));
      }
      return results;
    };

    LineBuffer.prototype.end = function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      if (args.length > 0) {
        this.write.apply(this, args);
      }
      if (this._buffer.length) {
        this.emit('data', this._buffer);
      }
      return this.emit('end');
    };

    return LineBuffer;

  })(Stream);

  exports.bufferLines = function(stream, callback) {
    var buffer;
    buffer = new LineBuffer(stream);
    buffer.on("data", callback);
    return buffer;
  };

  exports.mkdirp = function(dirname, callback) {
    var p;
    return fs.lstat((p = path.normalize(dirname)), function(err, stats) {
      var paths;
      if (err) {
        paths = [p].concat((function() {
          var results;
          results = [];
          while (p !== "/" && p !== ".") {
            results.push(p = path.dirname(p));
          }
          return results;
        })());
        return async.forEachSeries(paths.reverse(), function(p, next) {
          return fs.exists(p, function(exists) {
            if (exists) {
              return next();
            } else {
              return fs.mkdir(p, 0x1ed, function(err) {
                if (err) {
                  return callback(err);
                } else {
                  return next();
                }
              });
            }
          });
        }, callback);
      } else if (stats.isDirectory()) {
        return callback();
      } else {
        return callback("file exists");
      }
    });
  };

  exports.chown = function(path, owner, callback) {
    var error;
    error = "";
    return exec(["chown", owner, path], function(err, stdout, stderr) {
      if (err) {
        return callback(err, stderr);
      } else {
        return callback(null);
      }
    });
  };

  exports.pause = function(stream) {
    var onClose, onData, onEnd, queue, removeListeners;
    queue = [];
    onData = function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return queue.push(['data'].concat(slice.call(args)));
    };
    onEnd = function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return queue.push(['end'].concat(slice.call(args)));
    };
    onClose = function() {
      return removeListeners();
    };
    removeListeners = function() {
      stream.removeListener('data', onData);
      stream.removeListener('end', onEnd);
      return stream.removeListener('close', onClose);
    };
    stream.on('data', onData);
    stream.on('end', onEnd);
    stream.on('close', onClose);
    return function() {
      var args, i, len, results;
      removeListeners();
      results = [];
      for (i = 0, len = queue.length; i < len; i++) {
        args = queue[i];
        results.push(stream.emit.apply(stream, args));
      }
      return results;
    };
  };

  exports.sourceScriptEnv = function(script, env, options, callback) {
    var command, cwd, filename, ref;
    if (options.call) {
      callback = options;
      options = {};
    } else {
      if (options == null) {
        options = {};
      }
    }
    cwd = path.dirname(script);
    filename = makeTemporaryFilename();
    command = ((ref = options.before) != null ? ref : "true") + " &&\nsource " + (quote(script)) + " > /dev/null &&\nenv > " + (quote(filename));
    return exec(["bash", "-c", command], {
      cwd: cwd,
      env: env
    }, function(err, stdout, stderr) {
      if (err) {
        err.message = "'" + script + "' failed to load:\n" + command;
        err.stdout = stdout;
        err.stderr = stderr;
        return callback(err);
      } else {
        return readAndUnlink(filename, function(err, result) {
          if (err) {
            return callback(err);
          } else {
            return callback(null, parseEnv(result));
          }
        });
      }
    });
  };

  exports.getUserEnv = function(callback, defaultEncoding) {
    var filename;
    if (defaultEncoding == null) {
      defaultEncoding = "UTF-8";
    }
    filename = makeTemporaryFilename();
    return loginExec("exec env > " + (quote(filename)), function(err) {
      if (err) {
        return callback(err);
      } else {
        return readAndUnlink(filename, function(err, result) {
          if (err) {
            return callback(err);
          } else {
            return getUserLocale(function(locale) {
              var env;
              env = parseEnv(result);
              if (env.LANG == null) {
                env.LANG = locale + "." + defaultEncoding;
              }
              return callback(null, env);
            });
          }
        });
      }
    });
  };

  exec = function(command, options, callback) {
    if (callback == null) {
      callback = options;
      options = {};
    }
    return execFile("/usr/bin/env", command, options, callback);
  };

  quote = function(string) {
    return "'" + string.replace(/\'/g, "'\\''") + "'";
  };

  makeTemporaryFilename = function() {
    var filename, random, ref, timestamp, tmpdir;
    tmpdir = (ref = process.env.TMPDIR) != null ? ref : "/tmp";
    timestamp = new Date().getTime();
    random = parseInt(Math.random() * Math.pow(2, 16));
    filename = "pow." + process.pid + "." + timestamp + "." + random;
    return path.join(tmpdir, filename);
  };

  readAndUnlink = function(filename, callback) {
    return fs.readFile(filename, "utf8", function(err, contents) {
      if (err) {
        return callback(err);
      } else {
        return fs.unlink(filename, function(err) {
          if (err) {
            return callback(err);
          } else {
            return callback(null, contents);
          }
        });
      }
    });
  };

  loginExec = function(command, callback) {
    return getUserShell(function(shell) {
      var login;
      login = ["login", "-qf", process.env.LOGNAME, shell];
      return exec(slice.call(login).concat(["-i"], ["-c"], [command]), function(err, stdout, stderr) {
        if (err) {
          return exec(slice.call(login).concat(["-c"], [command]), callback);
        } else {
          return callback(null, stdout, stderr);
        }
      });
    });
  };

  getUserShell = function(callback) {
    var command;
    command = ["dscl", ".", "-read", "/Users/" + process.env.LOGNAME, "UserShell"];
    return exec(command, function(err, stdout, stderr) {
      var match, matches, shell;
      if (err) {
        return callback(process.env.SHELL);
      } else {
        if (matches = stdout.trim().match(/^UserShell: (.+)$/)) {
          match = matches[0], shell = matches[1];
          return callback(shell);
        } else {
          return callback(process.env.SHELL);
        }
      }
    });
  };

  getUserLocale = function(callback) {
    return exec(["defaults", "read", "-g", "AppleLocale"], function(err, stdout, stderr) {
      var locale, ref;
      locale = (ref = stdout != null ? stdout.trim() : void 0) != null ? ref : "";
      if (!locale.match(/^\w+$/)) {
        locale = "en_US";
      }
      return callback(locale);
    });
  };

  parseEnv = function(stdout) {
    var env, i, len, line, match, matches, name, ref, value;
    env = {};
    ref = stdout.split("\n");
    for (i = 0, len = ref.length; i < len; i++) {
      line = ref[i];
      if (matches = line.match(/([^=]+)=(.+)/)) {
        match = matches[0], name = matches[1], value = matches[2];
        env[name] = value;
      }
    }
    return env;
  };

}).call(this);
